apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetworld
spec:
  selector:
    matchLabels:
      app: dotnetworld
  replicas: 1 
  template: 
    metadata:
      labels:
        app: dotnetworld
    spec:
      containers:
      - name: dotnetworld
        image: vignesh203/dotnet:latest
        ports:
        - containerPort: 80
